---
title: "Gov 50 Final Project"
author: "Nishant Mishra"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



\newcommand{\noin}{\noindent}    
\newcommand{\Var}{\text{Var}}    
\newcommand{\Cov}{\text{Cov}}    


```{r}
library(tidyverse)
set.seed(50)
data <- read.csv('data/MERGED2018_19_PP.csv')
data <- data[data$DISTANCEONLY == 0, ]
data <- as.data.frame(data)
```

```{r}
common <- c('MD_EARN_WNE_P6', 'HIGHDEG', 'REGION', 'UGDS_WHITE', 'UGDS_BLACK', 'UGDS_HISP', 'UGDS_ASIAN', 'UGDS_AIAN', 'UGDS_NHPI', 'UGDS', 'UGDS_MEN', 'NPT4_PUB', 'NPT4_PRIV', 'PCIP04', 'PCIP05', 'PCIP09', 'PCIP11', 'PCIP12', 'PCIP14', 'PCIP23', 'PCIP26', 'PCIP27', 'PCIP38', 'PCIP42', 'PCIP45', 'PCIP50', 'PCIP51', 'PCIP52', 'PCIP54')

trad_cols <- c('ADM_RATE', 'SAT_AVG')

data <- data[, c(both_cols, trad_cols)]
data[data == ""] = NA
data[data == "NULL"] = NA

data <- as.data.frame(data)

completeFun <- function(data, desiredCols) {
  completeVec <- complete.cases(data[, desiredCols])
  return(data[completeVec, ])
}

data <- completeFun(data, c('MD_EARN_WNE_P6', 'HIGHDEG', 'REGION', 'UGDS_WHITE', 'UGDS_BLACK', 'UGDS_HISP', 'UGDS_ASIAN', 'UGDS_AIAN', 'UGDS_NHPI', 'UGDS', 'UGDS_MEN', 'PCIP04', 'PCIP05', 'PCIP09', 'PCIP11', 'PCIP12', 'PCIP14', 'PCIP23', 'PCIP26', 'PCIP27', 'PCIP38', 'PCIP42', 'PCIP45', 'PCIP50', 'PCIP51', 'PCIP52', 'PCIP54'))

trad <- data[!is.na(data$ADM_RATE) & !is.na(data$SAT_AVG), ]
trad <- sapply(trad, as.numeric)
trad <- as.data.frame(trad)
trad$HIGHDEG <-factor(trad$HIGHDEG, levels=0:4, labels=c("Non-degree granting", "Certificate degree", "Associate degree", "Bachelor's degree", "Graduate degree"))
trad$REGION <- factor(trad$REGION, levels=0:9, labels=c("U.S. Service Schools", "New England", "Mid East", "Great Lakes", "Plains", "Southeast", "Southwest", "Rocky Mountains", "Far West", "Outlying Areas"))

nontrad <- data[is.na(data$ADM_RATE) | is.na(data$SAT_AVG), ]
nontrad <- subset(nontrad, select = -c(ADM_RATE, SAT_AVG))
nontrad <- sapply(nontrad, as.numeric)
nontrad <- as.data.frame(nontrad)
nontrad$HIGHDEG <-factor(nontrad$HIGHDEG, levels=0:4, labels=c("Non-degree granting", "Certificate degree", "Associate degree", "Bachelor's degree", "Graduate degree"))
nontrad$REGION <- factor(nontrad$REGION, levels=0:9, labels=c("U.S. Service Schools", "New England", "Mid East", "Great Lakes", "Plains", "Southeast", "Southwest", "Rocky Mountains", "Far West", "Outlying Areas"))

hist(trad$MD_EARN_WNE_P6, xlab = "median salary", main="median salary after 6 years")
hist(log(trad$MD_EARN_WNE_P6), xlab = "log median salary", main="log median salary after 6 years" )

wilcox.test(x = trad$MD_EARN_WNE_P6, y = nontrad$MD_EARN_WNE_P6,
            alternative = 'two.sided',
            exact = FALSE,
            correct = FALSE,
            conf.int = TRUE)
```

```{r}
library(xtable)
trad$UGDS_ASIAN <- trad$UGDS_ASIAN * 100

lm.asian <- lm(log(MD_EARN_WNE_P6) ~ UGDS_ASIAN, data=trad)
xtable(summary(lm.asian))

plot(log(MD_EARN_WNE_P6) ~ UGDS_ASIAN, data=trad)
plot(lm.asian$residuals ~ lm.asian$fitted.values)
qqnorm(lm.asian$residuals)
qqline(lm.asian$residuals)
```

